# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: npm
    directory: "/" # Location of package manifests
    # Check the npm registry for updates at 8pm UTC
    schedule:
      interval: daily
      time: "20:00"
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 10
